Import("env")

xddp = Environment()

libs = Split("""
m
dl
stdc++
""")

xddp.Append(LIBS = libs)
xddp.Append(CCFLAGS = ['-std=c++0x','-g','-O3'])
xddp.Append(CPPDEFINES = env['CPPDEFINES'])
xddp.Append(CPPPATH = env.subst(env['CPPPATH']))

xddp.Program( target = 'xddp_console', source = 'xddp_thread.cpp' )

