/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Tue Jan 10 18:42:04 2017
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_6 1.80087
#define M_13 0.892582
#define M_14 1.02461
#define M_15 1.70011
#define M_16 1.40982
#define M_17 0.729921
#define M_18 0.666467

// center of mass
#define L_1_6 -0.0263911
#define L_2_6 -0.000582164
#define L_3_6 0.0526323
#define L_1_13 -0.000326968
#define L_2_13 -0.0235873
#define L_3_13 -0.000264965
#define L_1_14 0.00125916
#define L_2_14 -0.0168964
#define L_3_14 -0.0589033
#define L_1_15 0.000987201
#define L_2_15 0.000670373
#define L_3_15 -0.0757168
#define L_1_16 0.00246127
#define L_2_16 -0.00530996
#define L_3_16 -0.0859895
#define L_1_17 0.000880673
#define L_2_17 -0.000922249
#define L_3_17 0.000230385
#define L_1_18 0.0096921
#define L_2_18 -0.00904602
#define L_3_18 -0.06376

// inertia
#define IN_1_6 0.0051033
#define IN_3_6 0.00169205
#define IN_5_6 0.00624164
#define IN_6_6 1.72259e-05
#define IN_9_6 0.00245178
#define IN_1_13 0.000476723
#define IN_5_13 0.000545804
#define IN_9_13 0.000512686
#define IN_1_14 0.000916572
#define IN_5_14 0.0010485
#define IN_6_14 2.54929e-05
#define IN_9_14 0.000686372
#define IN_1_15 0.00389795
#define IN_2_15 1.78024e-06
#define IN_3_15 2.64033e-05
#define IN_5_15 0.00393608
#define IN_6_15 4.52271e-05
#define IN_9_15 0.000902187
#define IN_1_16 0.0040604
#define IN_2_16 1.12272e-05
#define IN_3_16 1.2261e-05
#define IN_5_16 0.00400565
#define IN_6_16 0.000518992
#define IN_9_16 0.00124141
#define IN_1_17 0.000320344
#define IN_2_17 7.63463e-06
#define IN_3_17 2.54302e-07
#define IN_5_17 0.000365844
#define IN_9_17 0.000360652
#define IN_1_18 0.00129448
#define IN_3_18 0.000200801
#define IN_5_18 0.00158518
#define IN_6_18 0.000275993
#define IN_9_18 0.00133268

// body point
//#define DPT_2_1 -0.023
//#define DPT_2_2 -0.0496
//#define DPT_3_3 -0.1024
//#define DPT_3_4 -0.1234
//#define DPT_3_6 -0.201
//#define DPT_3_8 -0.1
#define RIGHT 1
#define LEFT 0
// ============================================================ //

# endif
