
Import("env")

carm = env.Clone()
carm.Append(LIBPATH = ['$COMAN_SHARED_PATH/examples/lib/'])
carm.Append(LIBS = ['coman_shared','yaml-cpp'])

source =  ['test_boards_ctrl.cpp', 'test_main.cpp']

carm.Program('test_main', source  )

xddp = Environment()

libs = Split("""
m
dl
stdc++
""")

xddp.Append(LIBS = libs)
xddp.Append(CCFLAGS = ['-std=c++0x','-g','-pg','-O3'])
xddp.Append(CPPDEFINES=carm['CPPDEFINES'])

xddp.Program( target = 'xddp_console', source = ['xddp_thread.cpp'] )
